fun main(args: Array<String>) {
//    println(Problem_1.reverseWords("Hello World!"))
//    println(Problem_2.numberToString(2222))
//    println(Problem_3.simpleMultiplication((1..10).random()))
//    println(Problem_4.spinWords("Hey fellow warriors"))
//    println(Problem_6.removeChar("Sentence"))
//    println(Problem_7.stringToNumber("1234"))
//    println(Problem_8.feast("hello", "hello"))
//    println(Problem_9.addrevName("Hello World!"))
//    println(Problem_11.nextBiggerNumber(2398475))
//    println(Problem_12.accum("ZpglnRxqenUdkx"))
//    println(Problem_13.past(0, 1, 1))
//    println(Problem_14.plusOne(intArrayOf(1, 2, 3)))
//    println(Problem_15.outed(mapOf("tim" to 0, "jim" to 2, "randy" to 0, "sandy" to 7, "andy" to 0, "katie" to 5, "laura" to 1, "saajid" to 2, "alex" to 3, "john" to 2, "mr" to 0), "laura"))
//    println(Problem_16.printerError("kkkwwwaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmmmmxyz"))
//    println(Problem_17.findSmallestInt(listOf(111111, 2222, 33, 4, 888, 545, 6, 7, 8, 999999)))
//    println(Problem_18.lengthOfLastWord("Hello World"))
//    println(Problem_19.reverseLetter("Hello[17171717]World!"))
//    println(Problem_20.include(intArrayOf(1, 2, 3, 4, 5, 6), 2))
//    println(Problem_21.countPositivesSumNegatives(arrayOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -11, -12, -13, -14, -15)))
//    println(Problem_22.replace("ABCDE"))
//    println(Problem_23.wave("Hello World!"))
//    println(Problem_24.persistence(25))
//    println(Problem_25.fizzBuzz(25))
//    println(Problem_29.decode("XXIX"))
//    println(Problem_30.encryptThis("A wise old owl lived in an oak"))
//    println(Problem_32.isLeapYear(1984))
//    println(Problem_33.perimeter(7))
    println(Problem_34.sumParts(intArrayOf(0, 1, 3, 6, 10)))
}
